name: Deploy to AWS S3

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: "web development"
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1' 

      - name: Build project
        run: |
          npm install
          npm run build  # Si usas Vite, Tailwind o cualquier framework JS, compílalo

      - name: Deploy to S3
        run: |
          aws s3 sync ./dist/ s3://juegos-florales-upt/ --delete
